### PR TITLE
Remove use of C# dynamic to avoid bizarre crash

### LINKED ISSUE #44: Process crash when RPC error message is received without stack field
We have a crash dump where this JSON message is received by the Visual Studio process:

```json
{
  "jsonrpc": "2.0",
  "id": 3,
  "error": {
    "code": -32000,
    "message": "Object reference not set to an instance of an object.",
    "data": {
      "stack": "   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.GetProjectScope()\r\n   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsCoreAsync>d__20.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<DetermineAllSymbolsAsync>d__19.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.CodeAnalysis.FindSymbols.FindReferencesSearchEngine.<FindReferencesAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.<FindReferencesAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetTagsForReferencedSymbolAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsInCurrentProcessAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.<GetDocumentHighlightsAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.<GetDocumentHighlightsAsync>d__5.MoveNext()",
      "code": "-2147467261"
    }
  }
}
```

The crashing exception is:

```
+		$exception	{"'Newtonsoft.Json.Linq.JObject' does not contain a definition for 'stack'"}	Microsoft.CSharp.RuntimeBinder.RuntimeBinderException

 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinderController.SubmitError(Microsoft.CSharp.RuntimeBinder.Errors.CError pError) Line 19	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.LangCompiler.SubmitError(Microsoft.CSharp.RuntimeBinder.Errors.CParameterizedError error) Line 68	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Errors.ErrorHandling.ErrorTreeArgs(Microsoft.CSharp.RuntimeBinder.Errors.ErrorCode id, Microsoft.CSharp.RuntimeBinder.Errors.ErrArg[] prgarg) Line 102	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.Semantics.MemberLookup.ReportErrors() Line 845	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindProperty(System.Dynamic.DynamicMetaObjectBinder payload, Microsoft.CSharp.RuntimeBinder.RuntimeBinder.ArgumentObject argument, Microsoft.CSharp.RuntimeBinder.Semantics.LocalVariableSymbol local, Microsoft.CSharp.RuntimeBinder.Semantics.EXPR optionalIndexerArguments, bool fEventsPermitted) Line 1791	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.DispatchPayload(System.Dynamic.DynamicMetaObjectBinder payload, Microsoft.CSharp.RuntimeBinder.RuntimeBinder.ArgumentObject[] arguments, System.Collections.Generic.Dictionary<int, Microsoft.CSharp.RuntimeBinder.Semantics.LocalVariableSymbol> dictionary) Line 699	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(System.Dynamic.DynamicMetaObjectBinder payload, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> parameters, System.Dynamic.DynamicMetaObject[] args, out System.Dynamic.DynamicMetaObject deferredBinding) Line 246	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(System.Dynamic.DynamicMetaObjectBinder payload, System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> parameters, System.Dynamic.DynamicMetaObject[] args, out System.Dynamic.DynamicMetaObject deferredBinding) Line 172	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(System.Dynamic.DynamicMetaObjectBinder action, Microsoft.CSharp.RuntimeBinder.RuntimeBinder binder, System.Collections.Generic.IEnumerable<System.Dynamic.DynamicMetaObject> args, System.Collections.Generic.IEnumerable<Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo> arginfos, System.Dynamic.DynamicMetaObject onBindingError) Line 38	C#
 	Microsoft.CSharp.dll!Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject errorSuggestion) Line 68	C#
 	Newtonsoft.Json.dll!Newtonsoft.Json.Utilities.DynamicProxyMetaObject<System.__Canon>.BindGetMember.AnonymousMethod__0(System.Dynamic.DynamicMetaObject e) Line 61	C#
 	Newtonsoft.Json.dll!Newtonsoft.Json.Utilities.DynamicProxyMetaObject<Newtonsoft.Json.Linq.JObject>.CallMethodWithResult(string methodName, System.Dynamic.DynamicMetaObjectBinder binder, System.Linq.Expressions.Expression[] args, Newtonsoft.Json.Utilities.DynamicProxyMetaObject<Newtonsoft.Json.Linq.JObject>.Fallback fallback, Newtonsoft.Json.Utilities.DynamicProxyMetaObject<Newtonsoft.Json.Linq.JObject>.Fallback fallbackInvoke) Line 220	C#
 	Newtonsoft.Json.dll!Newtonsoft.Json.Utilities.DynamicProxyMetaObject<Newtonsoft.Json.Linq.JObject>.BindGetMember(System.Dynamic.GetMemberBinder binder) Line 60	C#
 	System.Core.dll!System.Dynamic.GetMemberBinder.Bind(System.Dynamic.DynamicMetaObject target, System.Dynamic.DynamicMetaObject[] args) Line 90	C#
 	System.Core.dll!System.Dynamic.DynamicMetaObjectBinder.Bind(object[] args, System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.ParameterExpression> parameters, System.Linq.Expressions.LabelTarget returnLabel) Line 107	C#
 	System.Core.dll!System.Runtime.CompilerServices.CallSiteBinder.BindCore<System.Func<System.Runtime.CompilerServices.CallSite, object, object>>(System.Runtime.CompilerServices.CallSite<System.Func<System.Runtime.CompilerServices.CallSite, object, object>> site, object[] args) Line 130	C#
 	System.Core.dll!System.Dynamic.UpdateDelegates.UpdateAndExecute1<object, object>(System.Runtime.CompilerServices.CallSite site, object arg0) Line 254	C#
 	StreamJsonRpc.dll!StreamJsonRpc.JsonRpcError.ErrorStack.get() Line 29	C#
 	StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.CreateExceptionFromRpcError(StreamJsonRpc.JsonRpcMessage response, string targetName) Line 756	C#
 	StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.InvokeCoreAsync.AnonymousMethod__0(StreamJsonRpc.JsonRpcMessage response) Line 636	C#
>	StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.HandleRpcAsync(string json) Line 1021	C#
 	StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync.AnonymousMethod__0()	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke() Line 680	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#
 	[Native to Managed Transition]	
```

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #44 (although we haven't figured out why C# dynamic fails sometimes).

This removes the last use of `dynamic` from the library.

### CODE REVIEW

File: src/StreamJsonRpc/DataContracts/JsonRpcError.cs [hunk 1]
```diff
@@ -14,16 +15,16 @@ internal JsonRpcError(int code, string message)
...
-        internal JsonRpcError(int code, string message, dynamic data)
+        internal JsonRpcError(int code, string message, JObject data)
         {
             this.Code = code;
             this.Message = message;
             this.Data = data;
         }
 
-        public string ErrorStack => this.Data?.stack;
+        public string ErrorStack => this.Data?["stack"]?.Type == JTokenType.String ? this.Data.Value<string>("stack") : null;
```
Comment (IlyaBiryukov) [inline src/StreamJsonRpc/DataContracts/JsonRpcError.cs]: These names repeat in several places. It would be better to use string constants for them.

Comment (AArnott) [inline src/StreamJsonRpc/DataContracts/JsonRpcError.cs]: Done.
