### PR TITLE
Include RPC server stack trace in RemoteInvocationException.ToString()

### LINKED ISSUE #369: RemoteInvocationException.ToString() return value should include remote callstack
If an exception occurs remotely and is communicated back across the RPC boundary, you get a RemoteInvocationException.  Calling ToString on it returns a string that includes only the local callstack.  It would be very helpful if the callstack could be made to include the remote portion of the callstack (which is available in the ErrorData property) as well.

### PR DESCRIPTION
**Pull request by AArnott**
It isn't always possible to do, but when the server provides a `CommonErrorData` object, we certainly can do it.
I endeavored to copy the string format that .NET uses for its own exception formatting, including for inner exceptions.

Closes #369

### CODE REVIEW

File: src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs [hunk 1]
```diff
@@ -83,5 +85,56 @@ public RemoteInvocationException(string? message, int errorCode, object? errorDa
         /// The default implementation of this method produces a <see cref="CommonErrorData"/> object.
         /// </remarks>
         public object? DeserializedErrorData { get; }
+
+        /// <inheritdoc/>
+        public override string ToString()
+        {
+            string result = base.ToString();
```
Comment (JoshuaBStevens) [inline src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs]: You could avoid calling base.ToString (for efficiency) if you're going to overwrite the result anyway.

File: src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs [hunk 2]
```diff
@@ -83,5 +85,56 @@ public RemoteInvocationException(string? message, int errorCode, object? errorDa
...
+
+            CommonErrorData? errorData = this.DeserializedErrorData as CommonErrorData;
+            if (errorData != null)
+            {
+                var builder = new StringBuilder(base.ToString());
```
Comment (JoshuaBStevens) [inline src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs]: You can use "result" instead of "base.ToString()" here.

File: src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs [hunk 3]
```diff
@@ -83,5 +85,56 @@ public RemoteInvocationException(string? message, int errorCode, object? errorDa
...
         /// </remarks>
         public object? DeserializedErrorData { get; }
+
+        /// <inheritdoc/>
+        public override string ToString()
+        {
+            string result = base.ToString();
+
+            CommonErrorData? errorData = this.DeserializedErrorData as CommonErrorData;
+            if (errorData != null)
```
Comment (JoshuaBStevens) [inline src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs]: These two lines could be written as "if (this.DeserializedErrorData is CommonErrorData errorData)", couldn't they?

File: src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs (hunk 2 above)
Comment (milopezc) [reply src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs]: This feels right to me in terms of readability. If the ToString() method affects the performance considerably then we should go with this, but I would suggest changing the name of the variable to baseString or something similar.
